services:
  iscpp-db:
    image: postgres:16
    container_name: iscpp-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${ISCPP_DB_USERNAME}
      POSTGRES_PASSWORD: ${ISCPP_DB_PASSWORD}
      POSTGRES_DB: ${ISCPP_DB_DATABASE}
    ports:
      - "${ISCPP_DB_PORT:-5432}:5432"
    volumes:
      - iscpp-db:/var/lib/postgresql/data

  iscpp-nginx:
    image: nginx:latest
    container_name: iscpp-nginx
    depends_on:
      - iscpp-app
    volumes:
      - iscpp-app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${ISCPP_APP_PORT:-8080}:80"

  iscpp-app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: iscpp-app
    restart: unless-stopped
    depends_on:
      - iscpp-db
    volumes:
      - iscpp-app:/var/www
    environment:
      ISCPP_APP_KEY: "${ISCPP_APP_KEY:-}"
      ISCPP_APP_DEBUG: ${ISCPP_APP_DEBUG:-false}
      ISCPP_APP_ENV: ${ISCPP_APP_ENV:-production}
      ISCPP_APP_URL: ${ISCPP_APP_URL:-http://localhost:8080}
      ISCPP_DB_CONNECTION: ${ISCPP_DB_CONNECTION:-pgsql}
      ISCPP_DB_HOST: iscpp-db
      ISCPP_DB_PORT: ${ISCPP_DB_PORT:-5432}
      ISCPP_DB_DATABASE: ${ISCPP_DB_DATABASE}
      ISCPP_DB_USERNAME: ${ISCPP_DB_USERNAME}
      ISCPP_DB_PASSWORD: ${ISCPP_DB_PASSWORD}
      ISCPP_BRANCH: ${ISCPP_BRANCH:-main}
      ISCPP_USER_DEFAULT_TIMEZONE: ${ISCPP_USER_DEFAULT_TIMEZONE:-'Europe/Berlin'}
      ISCPP_AUTO_UPDATE: ${ISCPP_AUTO_UPDATE:-false}
    entrypoint: ["sh", "/usr/local/bin/entrypoint.sh"]


volumes:
  iscpp-db:
  iscpp-app:
